server:
  port: 8080
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto
      port-header: x-forwarded-port
  servlet:
    session:
      cookie:
        same-site: None                 # necesario en iframe
        secure: true
smart:
  # For standalone testing only. In EHR launch, these come from `iss` and `launch` query params.
  fhirBase: "https://interopio.ontada.com/gateway/fhir/developerportalio/portal/gw-fhir"
  clientId: ""
  redirectUri: "https://<ngrokURL>/callback"
  scopes: "launch/patient openid fhirUser patient/Patient.read patient/MedicationRequest.read patient/DiagnosticReport.read patient/Observation.read"
  confidential: true        # si Ontada te da secret
  clientSecret: ""
  # launch: ""

spring:
  thymeleaf:
    cache: false
