server:
  port: 8080

smart:
  # For standalone testing only. In EHR launch, these come from `iss` and `launch` query params.
  fhirBase: "https://launch.smarthealthit.org/v/r4/sim/eyJrIjoiMSIsImoiOiIxIn0/fhir"
  clientId: "123HeliosClientTestID"
  redirectUri: "http://127.0.0.1:8080/callback"
  scopes: "launch/patient patient.read openid fhirUser offline_access"
  # launch: ""

spring:
  thymeleaf:
    cache: false
